# docker-compose.yml
services:
  etl:
    build: .
    env_file: .env
    volumes:
      - data:/data             # ⬅️ match your ../data -> /data
    command: ["python", "src/pipeline.py"]

volumes:
  data:
