# docker-compose.yml
services:
  etl:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data        # bind mount into the container (NOT a named volume)
    command: ["python", "src/pipeline.py"]

# no 'volumes:' section needed anymore

