name: Run ETL Pipeline

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC daily
  workflow_dispatch:

concurrency:
  group: etl-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        run: PYTHONPATH=src pytest tests/ -q

  run-etl:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure host data dir exists (for bind mount)
        run: mkdir -p data

      - name: Build & run ETL (Compose v2)
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from etl

      - name: Verify output exists
        run: |
          ls -la data
          test -f data/daily_metrics.csv
          echo "CSV verified successfully"
          
          # Check for charts
          if [ -d "data/charts" ]; then
            echo "Charts directory found:"
            ls -la data/charts/
          else
            echo "No charts directory found"
          fi

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily_metrics_csv
          path: data/daily_metrics.csv
          if-no-files-found: error
          retention-days: 7

      - name: Upload Charts artifacts
        uses: actions/upload-artifact@v4
        with:
          name: financial_charts
          path: data/charts/
          if-no-files-found: ignore
          retention-days: 7

  email-report:
    needs: run-etl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install deps
        run: pip install boto3 botocore

      - name: Download CSV artifact
        uses: actions/download-artifact@v4
        with:
          name: daily_metrics_csv
          path: artifacts

      - name: Download Charts artifacts
        uses: actions/download-artifact@v4
        with:
          name: financial_charts
          path: artifacts/charts
        continue-on-error: true

      - name: List all available artifacts (debug)
        uses: actions/download-artifact@v4
        with:
          path: all_artifacts
        continue-on-error: true

      - name: Debug artifact download
        run: |
          echo "Current directory contents:"
          ls -la
          echo "=== All downloaded artifacts ==="
          ls -la all_artifacts/ || echo "No all_artifacts directory found"
          echo "=== Target artifacts directory ==="
          ls -la artifacts/ || echo "Target artifacts directory not found"
          echo "=== Charts directory ==="
          ls -la artifacts/charts/ || echo "No charts directory found"
          echo "=== All files in workspace ==="
          find . -name "*.csv" -o -name "*.png" | head -20

      - name: Verify attachment exists (sanity check)
        run: |
          if [ ! -d "artifacts" ]; then
            echo "ERROR: artifacts directory does not exist"
            echo "This suggests the artifact download failed"
            exit 1
          fi
          ls -la artifacts
          if [ ! -f "artifacts/daily_metrics.csv" ]; then
            echo "ERROR: daily_metrics.csv not found in artifacts/"
            echo "Contents of artifacts directory:"
            ls -la artifacts/
            exit 1
          fi
          echo "SUCCESS: daily_metrics.csv found"

      - name: Send email via SES
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    us-west-2
          SENDER_EMAIL:          ${{ secrets.SENDER_EMAIL }}
          RECIPIENT_EMAIL:       ${{ secrets.RECIPIENT_EMAIL }}
          ATTACHMENT_PATH:       artifacts/daily_metrics.csv
        run: python src/send_report_email.py